font_family      Inconsolata Nerd Font
font_size 16.0
adjust_line_height 120%

disable_ligatures never

background_opacity 0.85
background_blur 40
dynamic_background_opacity yes

# Window margins
# Add margins (blank area outside the border) on all 4 sides
window_margin_width 10

# Keep margins even when only a single window is visible
single_window_margin_width 10 30 10 30

# Hide macOS title bar (window management handled by Aerospace)
hide_window_decorations titlebar-and-corners
